### ISSUE TITLE
zip file not appearing on MacBook Air 

### ISSUE THREAD

**Issue by B33K1ND** [Grum999/Newspaper#1]
Hello there! 
When I click to download the Newspaper zip file, it does not appear in my Downloads folder as a .zip file. Therefore, I cannot import it to Krita. Do you have any troubleshooting advice? Thank you very much, in advance!

**Comment by Grum999** [comment]
Hi @B33K1ND 

I'm not really aware about how Mac works... 

- Concerning your problem, does your Browser (Safari I guess?) return an error message about download?
- Do you have the same problem on all Newspaper zip releases or only with a the last one?
- If you try to download some zip archive from github from other project, do you have the same problem or only for Newspaper project?

Doing these tests maybe help to understand what's the problem.

Grum999

**Comment by Grum999** [comment]
No answers from 2years now, close issue :-)
